logging:
  pattern:
    dateformat: HH:mm:ss:SSS
  level:
    cn.itcast: debug
spring:
  rabbitmq:
    host: 192.168.93.132 # rabbitMQ的ip地址
    port: 5672 # 端口
    username: jensen
    password: 123456
    virtual-host: /
    listener:
      simple:
        prefetch: 1